[package]
name = "movastore-checkout"
version = "0.1.0"
edition = "2021"
rust-version = "1.91.0"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[profile.release]
opt-level = 3
overflow-checks = true
debug-assertions = false
lto = true
codegen-units = 1

[dependencies]
soroban-sdk = "28.0.0"

[dev-dependencies]
soroban-sdk = { version = "28.0.0", features = ["testutils"] }
